### PR TITLE
aodvv2: adapt to master and fix warnings

### PR DESCRIPTION
**Pull request by OlegHahm**

### CODE REVIEW

**Comment by OlegHahm** [comment]
Be careful when merging this PR: Since I don't know enough about the inner logic it might be that some changes break functionality. I focused on eliminating warnings.

**Comment by Lotterleben** [comment]
I'd rather not update to the new IPC API before it is merged... I'll check and cherry-pick your other commits, if that's okay.

**Comment by Lotterleben** [comment]
Concerning 6d9f037c: The packet_data.timestamp denotes when the packet which contained the info in the packet_data struct was received. However, the struct aodvv2_packet_data rreq_data from your commit is a fresh RREP created by the node itself. Since the timestamp is not transmitted, the timestamp will never be read in this case, and setting it is unnecessary overhead imho.

**Comment by Lotterleben** [comment]
Concerning 3912b34822 : You missed some `len`s :) I added a new commit that (hopefully) covers all of them. (5e764db7d)

**Comment by OlegHahm** [comment]
> I'd rather not update to the new IPC API before it is merged... I'll check and cherry-pick your other commits, if that's okay.

Sorry, I think this might have been formulated in a misleading way: I didn't mean _the_ new IPC API, but only the current version in master where `msg_send()` doesn't have a `blocking` parameter any longer.

**Comment by OlegHahm** [comment]
Concerning the timestamp: I feared that this wouldn't be correct, but the compiler was complaining that one struct member wasn't set and I thought _a_ valid is better than _no_ value here. ;-) But maybe it's clearer that the value is no required if you set it to `(timex_t) {0, 0}`.

**Comment by OlegHahm** [comment]
Concerning the `len` parameters: Yes, I know. I mostly focused on getting rid of the warnings and wasn't sure if there _is_ a reason where someone might indeed pass a negative value there.

**Comment by Lotterleben** [comment]
Concerning your first comment: #8006660 updates msg_send to msg_try_send, which is introduced by PR #1890, which is not merged yet.. I did of course update the parameters of msg_send() (see commit #7117c0cdc)

**Comment by OlegHahm** [comment]
Yes and no: the change is part of #1890, but has been already merged as part of separate PR (https://github.com/RIOT-OS/RIOT/pull/1847).

**Comment by Lotterleben** [comment]
I rebased yesterday and could've sworn I didn't find it anywhere... Nevermind my comments then, I'll cherry-pick that commit as well.

**Comment by smlng** [comment]
After our little coding session yesterday, I think you can close this one?!

**Comment by Lotterleben** [comment]
I think I could've closed this one a long time ago ^^ thanks for the hint.

**Pull request closed without merging**
